### ISSUE TITLE
user-sync quick install error

### ISSUE THREAD

**Issue by Tomomi99145** [bhunut-adobe/user-sync-quick-install#6]
Error is displayed when executing user-sync quick install.
Please tell me the solution.

Contents of error message.
↓

PS C:\Windows\System32\WindowsPowerShell\v1.0> iex ((New-Object System.Net.WebCl
ient).DownloadString('https://git.io/vbItN'))
Elevated.
Python Version 3.6.3150.0 already installed
Set PEX_ROOT System Environment Variable
Downloading user-sync-v2.2.2-windows-py363.tar.gz from https://github.com/adobe-
apiplatform/user-sync.py/releases/download/v2.2.2/user-sync-v2.2.2-windows-py363
.tar.gz
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure ch
annel.
At line:140 char:9

    Invoke-WebRequest -Uri $download -OutFile $downloadfile
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:Htt
pWebRequest) [Invoke-WebRequest], WebException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe
ll.Commands.InvokeWebRequestCommand

**Comment by bhunut-adobe** [comment]
@Tomomi99145 Thank you for reporting this issue. It seems like Github.com recently disabled the support for TLS 1.0 and TLS 1.1 on their website. Since Invoke-WebRequest will use TLS 1.0 as a default, this is cause the script to throw an error. I will look into the solution and get this fix as soon as possible.

**Comment by bhunut-adobe** [comment]
Resolved.  Tested and Verified.
